# permissions for end users to view labelstudioenterprises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labelstudioenterprise-viewer-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - labelstudioenterprises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - labelstudioenterprises/status
  verbs:
  - get
