# permissions for end users to edit labelstudioenterprises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labelstudioenterprise-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - labelstudioenterprises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - labelstudioenterprises/status
  verbs:
  - get
