apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lse-app.fullname" . }}-chart-info
  labels:
    {{- include "lse-app.labels" . | nindent 4 }}
data:
  lseVersion: "{{ coalesce .Values.global.image.tag .Chart.AppVersion }}"
  lseChartVersion: "{{ .Chart.Version }}"
